# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 486069c489ca82e2d9d960f8592c378aa2683649ecd62f2b4032864b04d2822d58bbaa90f500a4b5db35bfd91ee0c7d432fc2423d92c820d591383eb55604bc1

test:
  secret_key_base: 6a9bd4772c014a9dee9157353b34ab05f8a30fd43699cfe19cd1cc90193f500a47805ddefa1ae40f95627bad55c9e4558d2ed548c22c6cb28c38b5882e4c279b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
